Registration api
go-park-mail-ru/2024_2_VKatuny pull request #1
Opened 2024-09-25 07:10 UTC by Olgmuzalev13

2024-09-25 08:05 UTC, bqback requested changes

2024-09-25 08:05 UTC, bqback commented on main.go
> +	}
Надо бы ещё код ответа ставить через `w.WriteHeader()`. Без него вызов `w.Write()` автоматически ставит `200`, что означает успешную обработку.

2024-09-25 08:05 UTC, bqback commented on main.go
> +	})
Нет проверки на то, что пользователь уже существует. Для реализации в памяти можно сделать либо простую мапу с __RW__ мьютексом, либо синкмапу с ключами по адресу почты. После перехода в БД стоит запрашивать пользователя по почте и проверять, что вернулось -- 0 результатов/Ошибка об отсутствии результатов (смотря как этот запрос будет реализован), или 1 результат.

2024-09-25 08:05 UTC, bqback commented on main.go
> +	h.mu.Lock()
Стоит перейти на `RWMutex`, потому что чтение будет происходить чаще, чем запись, и использование `RLock` для мапы позволит нескольким горутинам читать из неё без блокирования, как это делает `Lock`.

2024-09-25 08:05 UTC, bqback commented on main.go
Насчёт чистой архитектуры.

Возьмём за пример `HandleCreateWorker`. Этот метод и запрос обрабатывает, и ID генерит, и пишет в хранилище пользователей.

В чистой архитектуре это выглядело бы так (с учётом коммента про проверку существования пользователя):
* [Слой delivery/handler] `HandleCreateWorker` декодирует запрос и вызывает метод слоя usecase/service
    * [Слой usecase/service] Метод обращается к методу слоя repository/storage, чтобы узнать, существует ли пользователь (что-то вроде `GetByEmail`)
        * [Слой repository/storage] Отдаёт информацию о существовании пользователя (объект пользователя), либо информацию о его отсутствии -- ошибку, например. Ошибку в любом случае придётся "прокидывать" наверх (в случае проблем при формировании запроса к БД и т. д.), поэтому можно сразу завести такую ошибку отдельно.
    * [Слой usecase/service] В зависимости от ответа метод либо передаёт ошибку обратно на слой delivery/handler, либо снова обращается к хранилищу, чтобы записать в него нового пользователя.
        * [Слой repository/storage] Записывает пользователя, отдаёт информацию о его создании -- новый ID, например. Точный вид отдаваемых данных лучше обсудить с фронтом -- если после регистрации переход на главную, там вряд ли нужно что-то кроме ID и имени с фамилией, если на профиль -- нужны будут все данные.
    * [Слой usecase/service] Передаёт ответ слоя repository/storage обратно в delivery/handler
* [Слой delivery/handler] В зависимости от полученного от usecase/service ответа проставляет в ответе код статуса и содержание ответа -- ошибку, либо данные, соответствующие успешной регистрации.

Такой формат значительно повышает читаемость и простоту изменений.

2024-09-25 08:05 UTC, bqback commented on main.go
> +	}
Создание хранилищ стоит вынести в отдельный файл -- их будет очень много, а `main` должен быть чистым.

2024-09-25 08:05 UTC, bqback commented on main.go
> +	})
Это тоже стоит вынести в отдельный файл, заведя в нём маршрутизатор (mux). Для `mux` на основе стандартной библиотеки есть инструкция [здесь](https://www.alexedwards.net/blog/an-introduction-to-handlers-and-servemuxes-in-go), например.

2024-09-25 08:05 UTC, bqback commented on main.go
> +		w.Header().Set("Content-Type", "application/json")
Это стоит вынести в отдельный `middleware`.

2024-09-25 08:05 UTC, bqback commented on main.go
> +	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
Согласно техническим требованиям ближе к концу, весь роутинг бэкенда должен начинаться с `/api/`. Стандартный маршрутизатор поддерживает саброуты (когда заводишь хендлер для /api/ и навешиваешь на него эндопинты с добавлением конкретного эндопинта), нестандартные и подавно.

Пока что можно прописать это ручками для каждого эндпоинта.

2024-09-25 08:05 UTC, bqback commented on main.go
> +func main() {
Весь код до этой функции надо разделить по файлам на основе [стандартного шаблона](https://github.com/golang-standards/project-layout).
Сам `main.go` также немного изменит своё местоположение.

2024-09-25 08:05 UTC, bqback commented on main.go
> +		ID:                 id,
ID обычно начинаются с 1, в этом случае получится так, что первый пользователь будет иметь ID 0.

2024-09-25 08:05 UTC, bqback commented on main.go
> +		WorkerPassword:  newUserInput.WorkerPassword,
Вообще без хэширования или иного шифрования? Надо исправить.

2024-09-25 08:05 UTC, bqback commented on main_test.go
> +// }
Надо либо убрать, либо реализовать.

2024-09-26 19:51 UTC, Olgmuzalev13 commented on main.go
> +	}
done

2024-09-26 19:53 UTC, Olgmuzalev13 commented on main.go
> +	}
done

2024-09-28 08:58 UTC, Olgmuzalev13 commented on main.go
> +		ID:                 id,
done

2024-09-28 09:23 UTC, Olgmuzalev13 commented on main.go
> +		WorkerPassword:  newUserInput.WorkerPassword,
done

2024-09-28 09:25 UTC, Olgmuzalev13 commented on main.go
> +	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
done

2024-09-28 10:00 UTC, Olgmuzalev13 commented on main.go
> +	})
done

2024-09-28 10:27 UTC, Olgmuzalev13 commented on main.go
> +	h.mu.Lock()
done

2024-09-29 10:07 UTC, bqback requested changes
Привет! Изменения по архитектуре слишком объёмные для того, чтобы выполнить их к РК1, поэтому пока без них, но стоит иметь в виду.
После РК обсудим ещё более подробно.

2024-09-29 10:07 UTC, bqback commented on usecase/service/employeradding.go
> +			EmployerPassword:   storage.HashPassword(newUserInput.EmployerPassword),
Хеширование -- немного дорогая по времени операция, я бы вынес её за пределы `Lock()`. Для регистрации работника тоже.
При логине тоже так -- сначала лок с извлечением пользователя, вне него проверка на соответствие.

2024-09-29 10:07 UTC, bqback commented on cmd/myapp/main.go
> +	workerHandler := handler.CreateWorkerHandler(&BD.HandlersWorker)
Я бы ещё больше разбивал хендлеры по смысловой группе, например так:
* Отдельно файлы под хендлеры с регистрацией и авторизацией, отдельно под, например, ленту вакансий и т. д.
    * В файле структура `RegistrationHandler`, её приватные поля -- минимальный набор необходимых сервисов, её методы -- функции типа `http.HandlerFunc`: `CreateWorker`, `CreateEmployer` и т. д., которые будут обращаться к сервисам
    * Есть отдельная функция, которая принимает эти сервисы и отдаёт структуру `Registration` с проставлеными полями.

Если каждый хендлер заводить отдельно перед его добавлением в mux, как это делается сейчас, это займёт крайне много кода. При инициализации сервера ты вызываешь этот билдер структуры с хендлерами, и потом её методы предоставляешь своему роутеру.

Сервисы и хранилище надо будет реализовать также -- структура с приватными полями, соответствующими более низкому слою, методы для обращения к этому слою, конструктор, проставляющий поля. Для структуры хранилища приватным полем была бы соответствующая мапа (мапа с зарегистрированными пользователями для регистрации и логина, мапа с активными сессиями, мапа с вакансиями), но я бы не рекомендовал начинать такой объём работ вплотную к РК, а после РК придётся перейти на БД. Для БД это, скорее всего, будет соединение к БД, если сразу сделаете Redis для сессий -- для хранилища авторизации это будет соединение к Redis.
Прямого доступа к хранилищу не должно быть ни у хендлеров, ни у сервисов.

2024-09-29 10:07 UTC, bqback commented on cmd/myapp/main.go
> +}
Надо подчистить перед сдачей.

2024-09-29 10:07 UTC, bqback commented on delivery/handler/employerhandler.go
> +			w.Write([]byte("{}"))
А всегда ли это будет такая ошибка? Надо будет завести раздельные ошибки под возможные варианты развития событий, и проверять их для возвращения разного ответа.
Вдруг у вас где-нибудь посреди программы паника при обработке нового пользователя, а новый пользователь получит ошибку, что он уже регистрировался.

2024-09-29 10:07 UTC, bqback commented on storage/getters.go
> +	fmt.Println("1")
Пока логгирование нормальным логгером не требуется по техническим требованиям, но привыкать писать внятные логи уже пора.
Либо убрать, либо довести до более осознанного вида.

2024-09-29 21:20 UTC, Olgmuzalev13 commented on usecase/service/employeradding.go
> +			EmployerPassword:   storage.HashPassword(newUserInput.EmployerPassword),
done

2024-09-29 21:30 UTC, Olgmuzalev13 commented on cmd/myapp/main.go
> +}
done

2024-09-29 21:30 UTC, Olgmuzalev13 commented on storage/getters.go
> +	fmt.Println("1")
done

2024-09-29 21:30 UTC, Olgmuzalev13 commented on delivery/handler/employerhandler.go
> +			w.Write([]byte("{}"))
done

2024-09-29 21:30 UTC, Olgmuzalev13 commented on main.go
> +		w.Header().Set("Content-Type", "application/json")
done

2024-10-02 14:36 UTC, merged