ID для запросов
go-park-mail-ru/2024_2_VKatuny pull request #23
Opened 2024-11-11 20:33 UTC by Ifelsik

Внесены изменения в middleware, которое теперь добавляет в контекст запроса request_id. Пока что id отображаются только в ручках, написанных по чистой архитектуре. В слои ниже request id пока не распространяется.

2024-11-11 21:11 UTC, Regikon approved these changes
В целом мелкие придирки, я одобряю

2024-11-11 21:11 UTC, Regikon commented on internal/logger/logger.go
> +		// ReportCaller: true,
Давай не будем оставлять кодокомментарии

2024-11-11 21:11 UTC, Regikon commented on internal/middleware/access_logger.go
> +		ctx := r.Context()
Вот эту строчку можно переместить в else блок

2024-11-11 22:23 UTC, Ifelsik commented on internal/logger/logger.go
> +		// ReportCaller: true,
Просто эта строчка добавляет отладочную информацию о месте возникновения ошибки (путь к файлу, функция, строка). В идеале наверно это надо в конфиг поместить, но пока так

2024-11-11 22:24 UTC, Ifelsik commented on internal/middleware/access_logger.go
> +		ctx := r.Context()
Это не так, потому что потом в функцию next передается контекст

2024-11-13 06:59 UTC, bqback commented on internal/logger/logger.go
> +		// ReportCaller: true,
Тогда стоит пометить это место как TODO, чтобы не забыть. Я бы, кстати, вместо отдельного флага сравнивал прокинутый в конфиге уровень логгирования с, например, `logrus.DebugLevel` (если мне не изменяет память, это просто `iota`, а значит `int`, а значит доступен оператор сравнения).

2024-11-13 07:22 UTC, bqback requested changes
Мне кажется, что стоит доработать `access_logger.go`

2024-11-13 07:22 UTC, bqback commented on cmd/app/main.go
>  	handlers = middleware.Panic(handlers)
Вообще миддлвар с обработкой паники должен быть самым "верхним", потому что на данный момент паничка в `AccessLogger` и `SetLogger` обработана им не будет. Можешь попробовать вызвать `panic()` в каком-нибудь из этих методов.

2024-11-13 07:22 UTC, bqback commented on internal/middleware/access_logger.go
> +		} else {
Могу ошибаться, но в этом случае в контексте будет отсутствовать ключ `dto.RequestIDContextKey`, и все вызовы к `SetRequestIDInLoggerFromRequest` будут писать в логи ошибку об отсутствии `requestID` в контексте. Предположу, что написать это один раз лучше, чем делать это на каждом шаге.

2024-11-13 07:22 UTC, bqback commented on internal/middleware/access_logger.go
> +			requestID = ""
`GenerateRequestID` при ошибке и так возвращает пустую строчку в `requestID`. Можно не писать.

2024-11-13 07:22 UTC, bqback commented on internal/middleware/access_logger.go
> +		ctx := r.Context()
Ветка else в принципе не нужна, потому что единственное, что меняется в исполнении функции при ошибке, это запись в логгер. В остальном логического смысла в разветвлении нет (с учётом комментов к 19-22).

2024-11-13 07:22 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_profile.go
> +	logger           *logrus.Entry
Почему Entry?

2024-11-16 14:22 UTC, Ifelsik commented on internal/pkg/applicant/delivery/applicant_profile.go
> +	logger           *logrus.Entry
Это экземпляр логгера, который наследует исходный logrus.Logger, что позволяет для конкретного handler/usecase/repository навесить необходимые поля, и которые будут существовать в рамках конкретной сущности.

2024-11-16 19:19 UTC, Ifelsik commented on cmd/app/main.go
>  	handlers = middleware.Panic(handlers)
Понимаю. даже думал об этом, просто там паниковать там не будем))

2024-11-16 19:27 UTC, Ifelsik commented on internal/middleware/access_logger.go
> +		} else {
В целом справедливо, поправил

2024-11-16 19:31 UTC, Ifelsik commented on internal/logger/logger.go
> +		// ReportCaller: true,
Добавил TODO

2024-11-16 19:31 UTC, Ifelsik commented on cmd/app/main.go
>  	handlers = middleware.Panic(handlers)
Поправил

2024-11-16 20:48 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_profile.go
> +	logger           *logrus.Entry
Понял, прикольно!

2024-11-16 20:56 UTC, bqback approved these changes

2024-11-16 20:56 UTC, merged