Тесты на вакансию
go-park-mail-ru/2024_2_VKatuny pull request #24
Opened 2024-11-13 00:01 UTC by Olgmuzalev13

2024-11-13 06:54 UTC, bqback requested changes
Привет!
В целом норм, только пара правок.

2024-11-13 06:54 UTC, bqback commented on internal/pkg/vacancies/repository/vacancies_postgres.go
> +	Db *sql.DB
Почему поле стало публичным?

2024-11-13 06:54 UTC, bqback commented on go.mod
> +	github.com/Masterminds/squirrel v1.5.4
Где используется? Не увидел в импортах в файлах в МРе.

2024-11-13 06:54 UTC, bqback commented on internal/pkg/vacancies/repository/vacancies_test.go
> +			name: "TestFail1",
Стоит подобрать более явные названия для тестов, чтобы было понятно, какой именно кейс тестируется.

Для успешных можно Ok оставить, наверное, только без 1.

2024-11-13 06:54 UTC, bqback commented on internal/pkg/vacancies/repository/vacancies_test.go
Сколько покрытие файла вышло? Для метода Create и Update, где 3-4 запроса, не помешает написать тест-кейсы с ошибками после разных запросов.

2024-11-13 16:40 UTC, Olgmuzalev13 commented on internal/pkg/vacancies/repository/vacancies_test.go
> +			name: "TestFail1",
done

2024-11-13 16:40 UTC, Olgmuzalev13 commented on go.mod
> +	github.com/Masterminds/squirrel v1.5.4
done

2024-11-13 16:42 UTC, Olgmuzalev13 commented on internal/pkg/vacancies/repository/vacancies_postgres.go
> +	Db *sql.DB
done

2024-11-14 07:52 UTC, bqback requested changes
Тесты на следующей неделе надо будет дописать, в остальном хорошо. Один коммент поправить и аппрув.

2024-11-14 07:52 UTC, bqback commented on internal/pkg/applicant/repository/applicant_test.go
> +				Email: "a.mail.ru",
А жто точно валидный адрес почты? Отдаётся другой.

2024-11-14 09:16 UTC, Olgmuzalev13 commented on internal/pkg/applicant/repository/applicant_test.go
> +				Email: "a.mail.ru",
да, опечатка, исправил

2024-11-15 20:46 UTC, Regikon commented
@bqback Думаю можно сливать, если нет еще вопросов к коду

2024-11-16 20:56 UTC, merged