Загрузка файлов при создании и обновлении вакансий
go-park-mail-ru/2024_2_VKatuny pull request #26
Opened 2024-11-16 13:45 UTC by Olgmuzalev13

Файлы выгружаутся в директорию из конфига также их имя добавляется в бд, файлы в бд не обновляются если пользователь не приложил фала при обновлении (не затирается страя аватарка)

2024-11-16 22:19 UTC, bqback requested changes
Привет, пара изменений, в целом по изменениям в ПР особо вопросов нет.

2024-11-16 22:19 UTC, bqback commented on cmd/app/main.go
> -	dbConnection, err := utils.GetDBConnection(conf.DataBase.GetDSN())
В #23 такая же строчка была, в чём причина?

2024-11-16 22:19 UTC, bqback commented on internal/configs/config.go
> +
В чём смысл геттера для публичных полей? Стоит заприватить тогда.

2024-11-16 22:19 UTC, bqback commented on internal/pkg/vacancies/delivery/vacancy.go
> +	fmt.Println(newVacancy)
Стоит заменить на logger.Debug, если это ещё нужно.

2024-11-16 22:19 UTC, bqback commented on internal/utils/file_loading.go
> +	}
Может через `slices.Contains()`?

2024-11-17 10:07 UTC, Olgmuzalev13 commented on internal/utils/file_loading.go
> +	}
ну мне нужно узнать скорее не что такие типы содержаться в файле, а то что не содержится других, поэтому не очень понимаю как это сделать с slices.Contains(). К тому же в дальнейшем может быть разное поведение для разных типов, для чего и пригодится case

2024-11-17 10:08 UTC, Olgmuzalev13 commented on internal/pkg/vacancies/delivery/vacancy.go
> +	fmt.Println(newVacancy)
done

2024-11-17 10:09 UTC, Olgmuzalev13 commented on internal/configs/config.go
> +
да, заприватил

2024-11-17 10:10 UTC, Olgmuzalev13 commented on cmd/app/main.go
> -	dbConnection, err := utils.GetDBConnection(conf.DataBase.GetDSN())
удалился пробел, ничего вроде не изменилось

2024-11-17 11:50 UTC, bqback commented on internal/utils/file_loading.go
> +	}
> а то что не содержится других

`if !slices.Containts(allowedTypes, i) { ... }`. Также можно сделать мапу `map[string]interface{}` и проверять наличие типа как `if _, ok := typeMape[i]; !ok { ... }`. 

Если разное поведение всё-таки понадобится, тогда можно и свитч сделать, сейчас смысла в этом не вижу.

2024-11-17 11:50 UTC, bqback commented on internal/configs/config.go
> +
Остальные поля тоже?

2024-11-17 11:53 UTC, bqback reviewed
Закончим последнюю ветку обсуждений и аппрув.

2024-11-17 12:04 UTC, Olgmuzalev13 commented on internal/utils/file_loading.go
> +	}
сделал

2024-11-17 12:11 UTC, bqback approved these changes

2024-11-17 12:11 UTC, merged