Переписывание ручек первого РК под чистую архитектуру
go-park-mail-ru/2024_2_VKatuny pull request #27
Opened 2024-11-16 14:16 UTC by Ifelsik

Ручки переписаны под чистую архитектуру
- feed вакансий
- регистрация
- логин
- логаут
- проверка авторизации  

Полностью осуществлен переход с http.Handler на хендлеры следующей сигнатуры `func foo(w http.ResponseWriter, r *http.Request)` , что позволит в дальнейшем переехать на gorilla/mux (необходимо для обработки запросов в соответствии с глаголами REST, а также для нормальной обработки slug'ов).  
В процессе теста функционала замечен *баг*, связанный с тем, что любой пользователь может поменять данные профиля любого другого пользователя. Также не требуется авторизация для изменения пользовательских данных. В данном ПР правиться это не будет.  
Функционал протещен в постмане.

2024-11-17 00:11 UTC, bqback requested changes
Привет!
Проделана огромная работа, текущее исполнение очень нравится. Не считая первого вопроса, в основном только среднего размера моменты.

2024-11-17 00:11 UTC, bqback commented on cmd/app/main.go
> +	applicantHandlers, err := applicant_delivery.NewApplicantProfileHandlers(app)
Я не ошибусь, если предположу, что текущая реализация через свич по методу проживёт ровно до перехода на gorilla/mux, где можно указывать методы?

2024-11-17 00:11 UTC, bqback commented on cmd/app/main.go
> +	Mux.HandleFunc("/api/v1/employer/vacancies/", employerHandlers.GetEmployerVacanciesHandler)
Стоит убрать создание и наполнение мультиплексера в какую-то отдельную функцию, очень большой мейн получается.

2024-11-17 00:11 UTC, bqback commented on internal/pkg/applicant/repository/applicant_inmem.go
> +	return nil, fmt.Errorf("such user doesn't exist")
Решили отказаться от предопределённых ошибок?

2024-11-17 00:11 UTC, bqback commented on internal/pkg/dto/dto.go
> +	Profile  interface{} `json:"profile"`
Почему так?

2024-11-17 00:11 UTC, bqback commented on internal/pkg/employer/repository/employer_inmem.go
Пора уже убрать, как мне кажется.

2024-11-17 00:11 UTC, bqback commented on internal/pkg/session/delivery/session_handlers.go
> +	if userType == dto.UserTypeApplicant {
Может быть тоже свитч, как в юзкейсе и репозитории? Опрятнее выглядит.

2024-11-17 07:54 UTC, Ifelsik commented on cmd/app/main.go
> +	applicantHandlers, err := applicant_delivery.NewApplicantProfileHandlers(app)
Именно так, свич временный костыль

2024-11-17 07:55 UTC, Ifelsik commented on cmd/app/main.go
> +	Mux.HandleFunc("/api/v1/employer/vacancies/", employerHandlers.GetEmployerVacanciesHandler)
Думал об этом, но пока не понимаю, куда это разместить

2024-11-17 07:58 UTC, Ifelsik commented on internal/pkg/dto/dto.go
> +	Profile  interface{} `json:"profile"`
Профиль может быть структурой как работодателя, так и соискателя, а у них поля отличаются

2024-11-17 07:59 UTC, Ifelsik commented on internal/pkg/applicant/repository/applicant_inmem.go
> +	return nil, fmt.Errorf("such user doesn't exist")
Вообще говоря нет, просто надо с Олегом договориться стандартизированных ошибках

2024-11-17 17:11 UTC, Ifelsik commented
Сейчас ручки авторизации не возвращают данных пользователя, только ID и userType

2024-11-17 17:11 UTC, Ifelsik commented on internal/pkg/session/delivery/session_handlers.go
> +	if userType == dto.UserTypeApplicant {
Отказался от такого возварщения данных о пользователе

2024-11-18 06:49 UTC, bqback commented on internal/pkg/dto/dto.go
> +	Profile  interface{} `json:"profile"`
Окей, справедливо, сам сталкивался с таким и прочувствовал всю боль от отсутствия наследственности классов в Go.

2024-11-18 07:00 UTC, bqback approved these changes

2024-11-18 07:00 UTC, bqback commented on internal/pkg/dto/dto.go
> +	Profile  interface{} `json:"profile"`
Возможно получится воспользоваться дженериками, по спеке вроде как можно указать "допустимые" типы. https://go.dev/ref/spec#Type_parameter_declarations

2024-11-18 07:03 UTC, bqback commented on cmd/app/main.go
> +	Mux.HandleFunc("/api/v1/employer/vacancies/", employerHandlers.GetEmployerVacanciesHandler)
В `internal/mux`, например, как это было сделано с миддлварями.

2024-11-18 09:00 UTC, Ifelsik commented on cmd/app/main.go
> +	Mux.HandleFunc("/api/v1/employer/vacancies/", employerHandlers.GetEmployerVacanciesHandler)
Ага, сделал, пока что просто перенес туда, потом подумаю как это сделать лаконичнее с помощью интерфейсов хендлеров

2024-11-18 09:00 UTC, Ifelsik commented on internal/pkg/dto/dto.go
> +	Profile  interface{} `json:"profile"`
Интересно, гляну, потом постараюсь подкрутить

2024-11-18 11:38 UTC, bqback approved these changes

2024-11-18 11:39 UTC, merged