Авторизация
go-park-mail-ru/2024_2_VKatuny pull request #3
Opened 2024-09-29 13:42 UTC by Olgmuzalev13

2024-09-29 16:14 UTC, bqback requested changes
Привет, всё посмотрел, постарался оставить только косметические правки.
На будущее -- не стоит плодить ветки от веток, для которых уже есть ПР. Сделал регистрацию, мы обсудили, замёрджил в dev, сделал авторизацию, мы обсудили, замёрджил в dev. 
Что-то пошло не так -- ветка от dev с фиксом, мёрдж обратно в неё же.
Отладил, причесал -- пр в main, я ещё раз пробегаюсь, мёрджу в main.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/authorized.go
> +		}
А если `err != nil`?

2024-09-29 16:14 UTC, bqback commented on delivery/handler/authorized.go
> +		if authorized == nil {
Очень неудачный нейминг, надо подумать над этим.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/authorized.go
> +			w.Write([]byte("{statusCode: 200, {id: " + strconv.Itoa(int(id)) + ", usertype: " + userType + "}}"))
Надо будет завести единую функцию для отправки ответа в http.ResponseWriter с указанием нужного кода.

2024-09-29 16:14 UTC, bqback commented on BD/inMemoryBD.go
> +	WorkerPassword  string // `json:"workerPassword"`
В чём смысл править тег, если он всё равно закомменчен?

2024-09-29 16:14 UTC, bqback commented on delivery/handler/authorized.go
> +				id, authorized = storage.GetEmployerBySession(&employerBase, session)
Мне кажется, перебирать два различных хранилища сессий, особенно так -- не очень хорошее исполнение.
Предлагаю три варианта на выбор:
* В куке помимо id сессии будет храниться и отсылаться тип аккаунта, чтобы сразу идти в нужное хранилище
* Хранилище сессий единое, в сессии вместе с информацией хранится тип пользователя и отдаётся фронту
* Хранилище сессий единое и полностью отделено от хранилища пользователей, содержа в себе только id сессии, id пользователя и тип пользователя. Информация запрашивается по id пользователя, если сессия существует и активна.

Для третьего варианта объём работы чуть больше, чем для второго, и гораздо больше, чем для первого, но при этом он самый реалистичный.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/employerhandler.go
> +		fmt.Println(11)
Вроде уже был комментарий про такие логи.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/employerhandler.go
>  			w.Write([]byte("{}"))
Стоит добавить сюда `return`.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/employerhandler.go
>  		}
И уменьшить уровень вложенности.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/employerhandler.go
> +			LoginFromAnyware(w, UserInputForToken)
Мне кажется, лучше сделать авторизацию после регистрации отдельным запросом.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/loginhandler.go
> +		}
А фронт как узнает о том, что ошибка произошла в целом и какая именно?

2024-09-29 16:14 UTC, bqback commented on delivery/handler/workerhandler.go
>  		}
Эдесь тоже уменьшить вложенность.

2024-09-29 16:14 UTC, bqback commented on main.go
> +}
Предположу, что это реализация коммента про архитектуру. Да, в общих чертах похоже на правду, детали обсудим после РК.
Если успеешь реализовать так -- отлично. Только, очевидно, это должно быть вне main.

2024-09-29 16:14 UTC, bqback commented on delivery/handler/authorized.go
> +		}
А это зачем?

2024-09-29 16:14 UTC, bqback commented on main.go
> +	r.HandleFunc("/logout", api.Logout)
Вижу, что в этой реализации использована горилла. В ней при создании эндпоинтов можно навесить допустимые методы. Давай сделаем.

2024-09-29 16:14 UTC, bqback commented on storage/setheaders.go
> +}
Мне кажется, это должно быть не в пакете `storage`.
В идеальной реализации это будет middleware, навешанный на весь роутер целиком. Миддлварей будет несколько, поэтому будет смысл завести под них отдельный пакет.

2024-09-29 16:14 UTC, bqback commented on usecase/service/employeradding.go
> +	//fmt.Println(rErr)
Тогда лучше совсем убрать.

2024-09-29 16:14 UTC, bqback commented on usecase/service/sessionadding.go
> +		workerBase.Mu.RUnlock()
Здесь разве не обычные Lock/Unlock? Мы же записываем, вроде.

2024-09-29 16:14 UTC, bqback commented on usecase/service/sessionadding.go
> +func TryAddSession(w http.ResponseWriter, newUserInput *BD.UserInput) (string, error) {
Очень много дублируемого кода, в частности вызванного раздельным хранением сессий. Если объединить, единственная зависимость от типа пользователя -- где мы его берём для сравнения, вся остальная функция работает одинаково.

2024-09-29 16:14 UTC, bqback commented on usecase/service/sessiondell.go
> +	_, ok1 := storage.GetEmployerBySession(&employerBase, session)
Сюда же коммент про хранилище сессий.

2024-09-30 07:51 UTC, Olgmuzalev13 commented on delivery/handler/authorized.go
> +		}
done

2024-09-30 07:52 UTC, Olgmuzalev13 commented on delivery/handler/authorized.go
> +		if authorized == nil {
done

2024-09-30 07:53 UTC, Olgmuzalev13 commented on BD/inMemoryBD.go
> +	WorkerPassword  string // `json:"workerPassword"`
эти комменты вроде не блокируют его как раз

2024-09-30 07:54 UTC, Olgmuzalev13 commented on delivery/handler/authorized.go
> +				id, authorized = storage.GetEmployerBySession(&employerBase, session)
done

2024-09-30 07:54 UTC, Olgmuzalev13 commented on usecase/service/sessionadding.go
> +		workerBase.Mu.RUnlock()
done

2024-09-30 07:55 UTC, Olgmuzalev13 commented on usecase/service/employeradding.go
> +	//fmt.Println(rErr)
done

2024-09-30 07:56 UTC, Olgmuzalev13 commented on usecase/service/sessiondell.go
> +	_, ok1 := storage.GetEmployerBySession(&employerBase, session)
ну код дальше будет разный так как это будут разные бд

2024-09-30 07:56 UTC, Olgmuzalev13 commented on delivery/handler/employerhandler.go
> +		fmt.Println(11)
done

2024-09-30 07:56 UTC, Olgmuzalev13 commented on delivery/handler/employerhandler.go
>  			w.Write([]byte("{}"))
done

2024-09-30 07:57 UTC, Olgmuzalev13 commented on delivery/handler/employerhandler.go
>  		}
это кусок кода пока не полностью отрабатывает это на будущее

2024-09-30 07:57 UTC, Olgmuzalev13 commented on delivery/handler/employerhandler.go
> +			LoginFromAnyware(w, UserInputForToken)
а как же переиспользование кода? тут как раз я пытаюсь его переиспользовать

2024-09-30 07:58 UTC, Olgmuzalev13 commented on delivery/handler/loginhandler.go
> +		}
done

2024-09-30 08:01 UTC, Olgmuzalev13 commented on delivery/handler/authorized.go
> +		}
обработка OPTIONS запроса для CORS политики

2024-11-01 16:20 UTC, closed without merging