Загрузка картинок в резюме и вакансиях, обновления профиля работник и работодателя с возможностью обновить аватарку
go-park-mail-ru/2024_2_VKatuny pull request #30
Opened 2024-11-20 13:27 UTC by Olgmuzalev13

2024-11-21 18:24 UTC, bqback requested changes
Привет!
Там коммент про `if`/`else`, к обновлению резюме и т. д. тот же вопрос, стоит подумать над каждым из случаев. В остальном всё хорошо.

2024-11-21 18:24 UTC, bqback commented on internal/configs/config.go
>  }
Снова вопрос про смысл геттера у публичного поля. Можно и убрать его, в принципе.

2024-11-21 18:24 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_profile.go
>  	ID, err := middleware.GetIDSlugAtEnd(w, r, "/api/v1/applicant/cv/")
Это ещё нужно? Вроде обсудили с Мишей получение слага на месте.

2024-11-21 18:24 UTC, bqback commented on internal/pkg/applicant/repository/applicant_postgres.go
> +	if newApplicantData.Avatar == "" {
Вам обязательно иметь `path_to_profile_avatar = null` для нормальной отрисовки на фронте?
Если нет, то можно было бы при пустом newApplicantData.Avatar тоже использовать запрос из ветки `else`, просто вместо нормального пути записывать путь до плейсхолдера.

2024-11-21 18:26 UTC, Regikon commented on internal/pkg/applicant/repository/applicant_postgres.go
> +	if newApplicantData.Avatar == "" {
Выражу мнение фронта. Я опираюсь на отсутствие этого поля, когда делаю решение о том, ставить ли стандартную картинку. Поэтому можно сказать, что мне это нужно. Других адекватных способов сообщить о том, что юзер ничего не загрузил, не вижу

2024-11-21 18:46 UTC, Olgmuzalev13 commented on internal/configs/config.go
>  }
не получается, не выводит поля с маленькой буквы
![image](https://github.com/user-attachments/assets/396facdc-7eed-4670-a237-5649e56c2478)

2024-11-21 19:58 UTC, Ifelsik commented on internal/pkg/applicant/delivery/applicant_profile.go
>  	ID, err := middleware.GetIDSlugAtEnd(w, r, "/api/v1/applicant/cv/")
Пока да, так как на гориллу не удалось пока переехать, а у Олега и так пока дел достаточно

2024-11-22 20:26 UTC, bqback commented on internal/configs/config.go
>  }
Не, геттер убрать, у тебя же поле и так публичное.

2024-11-22 21:41 UTC, Olgmuzalev13 commented on internal/configs/config.go
>  }
Да, действительно, убрал

2024-11-23 06:04 UTC, bqback approved these changes

2024-11-23 06:04 UTC, merged