Микросервис Сжатия
go-park-mail-ru/2024_2_VKatuny pull request #31
Opened 2024-11-20 21:32 UTC by Olgmuzalev13

Пока не готов совсем, но советы и замечания хотелось бы получить

2024-11-21 18:24 UTC, bqback commented
А он точно не будет конфликтовать с #30? Давай тот замёрджим и потом я пройдусь, есть ощущение, что часть будет повторяться.

2024-11-22 10:58 UTC, Ifelsik approved these changes
Вот с проверкой на nil бы разобраться, а так ок

2024-11-22 10:58 UTC, Ifelsik commented on cmd/compress_microservice/main.go
> +	}
Почему не используешь logrus?

2024-11-22 10:58 UTC, Ifelsik commented on configs/example-conf.yml
> +  portMicroservice: 8091
Укажи, что это порт именно микросервиса сжатия

2024-11-22 10:58 UTC, Ifelsik commented on microservices/compress/compress/repository/compress_microservice.go
> +}
Зачем эти заглушки?

2024-11-22 10:58 UTC, Ifelsik commented on microservices/compress/compress/delivery/compress_microservice.go
> +	err := cm.compressUsecase.DeleteFile(in.FileName)
Кстати, надо бы проверять, что `in != nil` и не только здесь, поможет избежать потенциальных ошибок, если структура не проинициализирована.
И еще по идее переданное в функцию поле надо проверять, что не nil, чтобы избежать паники с разименованием nil указателя

2024-11-22 10:58 UTC, Ifelsik commented on microservices/compress/compress/delivery/compress_microservice.go
> +	err := cm.compressUsecase.CompressAndSaveFile(in.FileName)
Надо бы проверять, что 
`in != nil`, и вообще надо бы везде, где передается надо проверять, чтобы избежать разименования структуры с nil указателем

2024-11-22 18:31 UTC, Olgmuzalev13 commented on configs/example-conf.yml
> +  portMicroservice: 8091
done

2024-11-22 18:32 UTC, Olgmuzalev13 commented on cmd/compress_microservice/main.go
> +	}
надо, но придется продублировать код из монолита

2024-11-22 18:32 UTC, Olgmuzalev13 commented on microservices/compress/compress/repository/compress_microservice.go
> +}
Заглушки чистая архитектура, проверки на nil и прочую логику вообще не добавлял еще

2024-11-27 10:37 UTC, bqback requested changes
Привет, там ещё от Миши комменты, успеешь посмотреть всё?

2024-11-27 10:37 UTC, bqback commented on cmd/compress_microservice/main.go
> +	}
Тогда нужно вынести в отдельную функцию, если дублируемого кода много.

2024-11-27 10:37 UTC, bqback commented on internal/pkg/applicant/usecase/applicant_profile.go
> +	fmt.Println("compress")
Тоже поменять на запись через логгер, в #34 вроде писал.

2024-11-27 10:37 UTC, bqback commented on internal/pkg/file_loading/usecase/file_loading.go
> +	conf := configs.ReadConfig("./configs/conf.yml")
Надо бы это сохранять при инициализации usecase, каждый раз открывать конфиг нет смысла, если у вас не предвидится hot reload конфигов. Но в таком случае это надо сделать вообще везде.

2024-11-27 10:41 UTC, Olgmuzalev13 commented on internal/pkg/applicant/usecase/applicant_profile.go
> +	fmt.Println("compress")
done

2024-11-27 10:43 UTC, Olgmuzalev13 commented on microservices/compress/compress/delivery/compress_microservice.go
> +	err := cm.compressUsecase.DeleteFile(in.FileName)
done

2024-11-27 10:43 UTC, Olgmuzalev13 commented on microservices/compress/compress/delivery/compress_microservice.go
> +	err := cm.compressUsecase.CompressAndSaveFile(in.FileName)
done

2024-11-27 10:44 UTC, Olgmuzalev13 commented on cmd/compress_microservice/main.go
> +	}
решили не дублировать, лежит в общей папке

2024-11-27 10:47 UTC, Olgmuzalev13 commented on internal/pkg/file_loading/usecase/file_loading.go
> +	conf := configs.ReadConfig("./configs/conf.yml")
done

2024-11-27 10:49 UTC, merged