Тест delivery резюме
go-park-mail-ru/2024_2_VKatuny pull request #32
Opened 2024-11-21 19:54 UTC by Ifelsik

Написаны тесты для cv:
* Сгенерены моки для всех usecase доменов  
* Моки исключены из подсчета покрытия  
 * Добавлена команда `mock-gen` в makefile для генерации моков

2024-11-21 19:55 UTC, Ifelsik commented
Тесты на создание и получение резюме жиденькие, но переписывать их пока не буду в связи с нехваткой времени

2024-11-22 20:49 UTC, bqback requested changes

2024-11-22 20:49 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_test.go
> +		registrationForm interface{} // dto.ApplicantRegistrationForm
Почему так?

2024-11-22 20:49 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_test.go
> +					"id":       float64(applicantID),
Какой float О_о?

2024-11-22 20:49 UTC, bqback commented on internal/pkg/cvs/delivery/cvs_test.go
> +// TODO: implement tests for SearchCVHandler
Ждём пуллреквеста с категориями?

2024-11-23 21:46 UTC, Ifelsik commented on internal/pkg/applicant/delivery/applicant_test.go
> +		registrationForm interface{} // dto.ApplicantRegistrationForm
для того, чтобы можно было передать туда рандом структуру, которая не сможет маршализироваться

2024-11-23 21:49 UTC, Ifelsik commented on internal/pkg/applicant/delivery/applicant_test.go
> +					"id":       float64(applicantID),
Вот так анмаршалит библа интерфейсы, то есть я в маршализируемой структуре имею поле, которое не является другой структурой, а интерфейсом. В этом случае, если в интерфейс передать структуру, то он приводится к мапе интерфейсов, где любые int меняются на float. Такая магия

2024-11-24 16:03 UTC, Ifelsik commented on internal/pkg/cvs/delivery/cvs_test.go
> +// TODO: implement tests for SearchCVHandler
Ждем пока, когда пр Олега сольете в dev

2024-11-24 21:33 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_test.go
> +					"id":       float64(applicantID),
А почему бы не писать в body результат json.Marshal(user)?

2024-11-24 21:33 UTC, bqback commented on internal/pkg/applicant/delivery/applicant_test.go
> +		registrationForm interface{} // dto.ApplicantRegistrationForm
Мне кажется, что в таком случае лучше прокинуть пустое тело непосредственно в подготовке теста, и сделать тип конкретным.

2024-11-27 10:57 UTC, bqback approved these changes

2024-11-27 11:51 UTC, merged