Категории на вакансии
go-park-mail-ru/2024_2_VKatuny pull request #33
Opened 2024-11-21 23:02 UTC by Olgmuzalev13

2024-11-22 20:46 UTC, bqback requested changes

2024-11-22 20:46 UTC, bqback commented on internal/pkg/dto/dto.go
> +	PositionCategoryName sql.NullString `json:"positionCategoryName"`
Не хотите попробовать [что-нибудь эдакое](https://stackoverflow.com/a/51961903/7971750) вместо заведения двух структур?

2024-11-22 20:46 UTC, bqback commented on internal/pkg/vacancies/vacancies.go
>  	Create(vacancy *dto.JSONVacancy) (uint64, error) // TODO: should accept DTO not a model
Сделали же вроде?

2024-11-22 21:30 UTC, Olgmuzalev13 commented on internal/pkg/vacancies/vacancies.go
>  	Create(vacancy *dto.JSONVacancy) (uint64, error) // TODO: should accept DTO not a model
да, убрал

2024-11-22 21:34 UTC, Olgmuzalev13 commented on internal/pkg/dto/dto.go
> +	PositionCategoryName sql.NullString `json:"positionCategoryName"`
Ну вообще такое наверное нет, потому что это надо будет держать в уме, что у нас по проекту ходит структура со странным типом, потому что этот способ только проблему маршализации решает, а что потом где-нибудь обратимся к полю не так и кастовать придется, когда будем передавать это поле строкой в репозиторий слой для поиска в бд

2024-11-23 06:05 UTC, bqback commented on internal/pkg/dto/dto.go
> +	PositionCategoryName sql.NullString `json:"positionCategoryName"`
Окей, справедливо.

2024-11-23 06:05 UTC, bqback approved these changes

2024-11-23 06:05 UTC, merged