Защита от CSRF
go-park-mail-ru/2024_2_VKatuny pull request #46
Opened 2024-12-09 23:41 UTC by Ifelsik

Выбран stateless подход, который шифрует ID сессии, ID пользователя и его тип и отправляет его с заголовком запроса на фронт.
На запрос к `/api/v1/authorized` вместе с кукой также отдаётся `X-CSRF-Token` с TTL в 30 мин.
На ручки, требующие защиты навешивается миддлвара, которая расшифровывает и сравнивает этот токен с данными сессии

2024-12-09 23:43 UTC, Ifelsik commented
Пока мидлвары не навесил

2024-12-10 19:33 UTC, Ifelsik commented
Мидлвары установлены

2024-12-15 00:30 UTC, bqback requested changes
Небольшая правка и аппрув.

2024-12-15 00:30 UTC, bqback commented on internal/middleware/csrf_protection.go
> +			if err == utils.ErrTokenExpired {
Лучше через `errors.Is`.

2024-12-15 01:13 UTC, Ifelsik commented on internal/middleware/csrf_protection.go
> +			if err == utils.ErrTokenExpired {
поправил

2024-12-15 13:59 UTC, bqback approved these changes

2024-12-15 13:59 UTC, merged