made wrapper that sets up CORS headers, hardcode constants replaced by http constants
go-park-mail-ru/2024_2_VKatuny pull request #6
Opened 2024-10-02 23:01 UTC by Ifelsik

2024-10-14 21:52 UTC, bqback requested changes
Привет! К сожалению, чистая архитектура пока только виднеется где-то на горизонте, и придётся много поработать над тем, чтобы её догнать.

Я вижу, что в корне проекта лежит папка `article`, явно вдохновлённая 8 частью лекции, но на этом вдохновление заканчивается. Нет ни интерфейсов (как в соседней с `article` папке `domain`, либо в папках `items` или `user` [10 части лекции](https://github.com/go-park-mail-ru/lectures/tree/master/5-architecture/10_crudapp/internal/pkg), ни чёткого разделения по слоям для отдельно взятой сущности.

Даже если оттолкнуться от обратного и спроектировать приложение не через domain driven design, как в вышеупомянутых примерах, а просто отдельно хранить хендлеры, отдельно сервисы, отдельно хранилища, как выходит сейчас -- в папках (уже) лежит куча файлов с одной функцией на файл, а вам надо реализовать ещё от 12 до 18 продуктовых требований (смотря как считать CRUDы). Их надо будет объединить по смысловым группам (в одном файле все хендлеры по авторизации, все хендлеры по вакансиям, и так для каждого слоя и каждой сущности), а также разбить все типы из `inMemoryBD.go`.

Правки займут много времени и точно не один раунд. Вам надо хорошо подумать над потенциальным объёмом работы и решить, что проще -- переделывать имеющееся, или переписать заново с ориентиром на примеры правильной реализации. Ни одно продуктовое требование ко второму РК в этой ветке ещё не начато.

2024-10-14 21:52 UTC, bqback commented on BD/inMemoryBD.go
> +// type userType string
Решили не делать?

2024-10-14 21:52 UTC, bqback commented on article/repository/employeradding.go
> +	_, err := GetEmployerByEmail(newUserInput.EmployerEmail)
Вот такие моменты должны быть вынесены в бизнес-логику в слое service. Сервис пытается получить из хранилища пользователя по почте, получилось -- пользователь уже есть, отдаёт в хендлер ошибку; не получилось -- такого пользователя нет и его можно регистрировать. Вызывать методы хранилища в методах хранилища нельзя (можно, но очень-очень-очень плохо и сразу приведёт к 0 баллов за архитектуру).

2024-10-14 21:52 UTC, bqback commented on article/repository/sessionadding.go
> +func AddSession(w http.ResponseWriter, newUserInput *BD.UserInput) (string, error) {
А ResponseWriter здесь зачем? Не вижу, чтобы применялось.

2024-10-14 21:52 UTC, bqback commented on article/usecase/service/hashers.go
В текущем виде содержимое папки service вместо бизнес-логики скорее похоже на пакет utils, потому что здесь кроме хэширования и генерации строки ничего нет.

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/workerhandler.go
> +			log.Printf("error while unmarshalling employer  JSON: %s", err)
Тут точно такая ошибка?

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/vacancies.go
> +		if ok != nil {
Это тогда err, наверное, а не ok.

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/vacancies.go
> +			UniversalMarshal(w, http.StatusBadRequest, BD.ErrorMessages{405, "offset is empty"})
Писал в лс в указание кодов ошибок через пакет `net/http`, а не хардкод `405`, и на РК1 вам за это сделали замечание. Надо исправить.

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/vacancies.go
> +			UniversalMarshal(w, http.StatusBadRequest, BD.ErrorMessages{405, "offset isn't number"})
Статус в `BD.ErrorMessages` не совпадает здесь и далее с логами и статусом, проставляемым в ответ (в логах правильно).

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/middleware/optionshandler.go
А зачем эти два файла в МР тогда, если они полностью deprecated?

2024-10-14 21:52 UTC, bqback commented on cmd/app/main.go
Почему два `main.go`?

2024-10-14 21:52 UTC, bqback commented on article/repository/sessionadding.go
> +		workerBase.Mu.Unlock()
Тоже относится к бизнес-логике и по-хорошему должно лежать в слое service: ищем пользователя по логину, не нашёлся -- сразу отдаём ошибку в хендлер, нашёлся -- сравниваем хеши, в случае успеха генерим сессию, записываем её в хранилище, отдаём в хендлер, в случае провала ошибка в хендлер.

2024-10-14 21:52 UTC, bqback commented on article/repository/getbysession.go
>  	id, err := table.Sessions[session.Value]
А вот здесь (в обоих методах, и в getbyemail.go) в сигнатуре должно быть `id, ok`. Что такое `err == true`, почему "ошибка правда" означает, что всё прошло успешно, и зачем писать `err == true`, если оно и так булево?

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/logouthandler.go
> +	return HttpHeadersWrapper(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
У вас в законченном проекте будет штук 20 хендлеров и минимум 4 миддлвера (panic recovery, JSON, CORS, логгирование и навес request ID -- техническое требование второго РК). Мне кажется, подобная конструкция в таком случае займёт безумно много места и убьёт весь смысл миддлвера как миддлвера, потому что сейчас он навешивается вручную на каждый эндпоинт и мало чем отличается от прописывания содержимого в каждом хендлере ручками.

Настоятельно рекомендую вчитаться в [пример миддлверов с лекции](https://github.com/go-park-mail-ru/lectures/blob/master/5-architecture/2_middleware/1_middleware/1_middleware.go).

2024-10-14 21:52 UTC, bqback commented on article/delivery/handler/authorized.go
> +		}
Всё ещё считаю такой подход плохим, пора уже реализовать БД и столкнуться с лишним запросом.

2024-10-17 13:46 UTC, Olgmuzalev13 commented on article/delivery/handler/workerhandler.go
> +			log.Printf("error while unmarshalling employer  JSON: %s", err)
done

2024-10-17 13:46 UTC, Olgmuzalev13 commented on article/delivery/handler/vacancies.go
> +		if ok != nil {
done

2024-10-17 13:51 UTC, Olgmuzalev13 commented on article/delivery/handler/vacancies.go
> +			UniversalMarshal(w, http.StatusBadRequest, BD.ErrorMessages{405, "offset is empty"})
done

2024-10-17 13:51 UTC, Olgmuzalev13 commented on article/delivery/handler/vacancies.go
> +			UniversalMarshal(w, http.StatusBadRequest, BD.ErrorMessages{405, "offset isn't number"})
done

2024-10-17 14:07 UTC, Olgmuzalev13 commented on cmd/app/main.go
done

2024-10-17 14:10 UTC, Olgmuzalev13 commented on article/repository/getbysession.go
>  	id, err := table.Sessions[session.Value]
done

2024-10-17 14:13 UTC, Olgmuzalev13 commented on article/repository/sessionadding.go
> +func AddSession(w http.ResponseWriter, newUserInput *BD.UserInput) (string, error) {
done

2024-10-17 14:14 UTC, Olgmuzalev13 commented on BD/inMemoryBD.go
> +// type userType string
пока да

2024-10-17 14:18 UTC, Olgmuzalev13 commented on article/delivery/handler/middleware/optionshandler.go
сохранил код для возможного использования в middleware потом уберу

2024-10-17 14:22 UTC, Olgmuzalev13 commented on article/usecase/service/hashers.go
не нашел описания папки utils, что там должно храниться?

2024-10-20 19:23 UTC, closed without merging

2024-10-20 19:24 UTC, Ifelsik commented
Слишком много мусора. Как сделаем чистую архитектуру создадим новый ПР